/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (Album.as).
 */

package org.graniteds.tide.model {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;
    import mx.collections.ListCollectionView;
    import org.granite.collections.IPersistentCollection;
    import org.granite.meta;

    use namespace meta;

    [Bindable]
    public class AlbumBase implements IExternalizable {

        private var __initialized:Boolean = true;
        private var __detachedState:String = null;

        private var _albumTracks:ListCollectionView;
        private var _duration:Duration;
        private var _id:String;
        private var _name:String;
        private var _version:int;
        private var _year:int;

        meta function isInitialized(name:String = null):Boolean {
            if (!name)
                return __initialized;

            var property:* = this[name];
            return (
                (!(property is Album) || (property as Album).meta::isInitialized()) &&
                (!(property is IPersistentCollection) || (property as IPersistentCollection).isInitialized())
            );
        }

        public function set albumTracks(value:ListCollectionView):void {
            _albumTracks = value;
        }
        public function get albumTracks():ListCollectionView {
            return _albumTracks;
        }

        public function set duration(value:Duration):void {
            _duration = value;
        }
        public function get duration():Duration {
            return _duration;
        }

        public function set id(value:String):void {
            _id = value;
        }
        public function get id():String {
            return _id;
        }

        public function set name(value:String):void {
            _name = value;
        }
        public function get name():String {
            return _name;
        }

        public function set version(value:int):void {
            _version = value;
        }
        public function get version():int {
            return _version;
        }

        public function set year(value:int):void {
            _year = value;
        }
        public function get year():int {
            return _year;
        }

        public function readExternal(input:IDataInput):void {
            __initialized = input.readObject() as Boolean;
            __detachedState = input.readObject() as String;
            if (meta::isInitialized()) {
                _albumTracks = input.readObject() as ListCollectionView;
                _duration = input.readObject() as Duration;
                _id = input.readObject() as String;
                _name = input.readObject() as String;
                _version = input.readObject() as int;
                _year = input.readObject() as int;
            }
            else {
                _id = input.readObject() as String;
            }
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(__initialized);
            output.writeObject(__detachedState);
            if (meta::isInitialized()) {
                output.writeObject(_albumTracks);
                output.writeObject(_duration);
                output.writeObject(_id);
                output.writeObject(_name);
                output.writeObject(_version);
                output.writeObject(_year);
            }
            else {
                output.writeObject(_id);
            }
        }
    }
}